// <auto-generated />
using System;
using DeliverySoftware.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeliverySoftware.Migrations
{
    [DbContext(typeof(DeliveryDBContext))]
    [Migration("20230419200739_AddedDateToDeliveries2")]
    partial class AddedDateToDeliveries2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeliverySoftware.Business.Delivery.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentDrop")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfPackages")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VanUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Deliveries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentDrop = 1,
                            Date = new DateTime(2023, 4, 19, 21, 7, 38, 942, DateTimeKind.Local).AddTicks(4699),
                            NumberOfPackages = 1,
                            Status = 1,
                            UID = new Guid("3f3cf1cd-131d-4d05-93b9-21dbd082fcac"),
                            VanUID = new Guid("f2b87d27-d4d8-425e-8df8-b3e7bf7f6460")
                        });
                });

            modelBuilder.Entity("DeliverySoftware.Business.Delivery.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CustomerUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeliveryUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DropNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsAssignedToDelivery")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerUID = new Guid("52fac4db-3d93-46bc-81ef-f33aed467669"),
                            DeliveryUID = new Guid("3f3cf1cd-131d-4d05-93b9-21dbd082fcac"),
                            Description = "Big box of rocks",
                            DropNumber = 1,
                            IsAssignedToDelivery = true,
                            IsDelivered = false,
                            Size = 10,
                            TrackingCode = "TESTPKG666",
                            UID = new Guid("0809ccb1-61f2-4ccc-9296-b24f6b138803")
                        },
                        new
                        {
                            Id = 2,
                            CustomerUID = new Guid("751e25c8-68ba-49dc-b1de-15fcb0bf210f"),
                            DeliveryUID = new Guid("3f3cf1cd-131d-4d05-93b9-21dbd082fcac"),
                            Description = "Big box of bolts",
                            DropNumber = 2,
                            IsAssignedToDelivery = true,
                            IsDelivered = false,
                            Size = 10,
                            TrackingCode = "TESTPKG123",
                            UID = new Guid("721a28e5-03b7-4c9a-863a-53d58e23d64a")
                        });
                });

            modelBuilder.Entity("DeliverySoftware.Business.Fleet.Van", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid?>("DriverUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Vans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            DriverUID = new Guid("16776aef-a5ff-424d-be7e-ea3fd591ce90"),
                            Registration = "WK04 DHC",
                            UID = new Guid("f2b87d27-d4d8-425e-8df8-b3e7bf7f6460")
                        });
                });

            modelBuilder.Entity("DeliverySoftware.Business.Users.DeliveryUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Forename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HouseNumber")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "751e25c8-68ba-49dc-b1de-15fcb0bf210f",
                            AccessFailedCount = 0,
                            Address = "306 Sinfin Avenue, Derby, UK",
                            ConcurrencyStamp = "0c22d31d-3ee4-4879-9783-9857d4e9e030",
                            Email = "petelampy@gmail.com",
                            EmailConfirmed = true,
                            Forename = "Annika",
                            HouseNumber = 306,
                            LockoutEnabled = false,
                            NormalizedEmail = "PETELAMPY@GMAIL.COM",
                            NormalizedUserName = "CUSTOMERLOGON",
                            PasswordHash = "AQAAAAIAAYagAAAAEJiR++CyYvTwlQmVeYFxnVN8wQ5Qps82ShVyO+2RPwFZO+owWUAhUF1kmoeeItxCJw==",
                            PhoneNumberConfirmed = false,
                            PostCode = "DE24 9QX",
                            SecurityStamp = "ffc3f231-28cb-418e-abff-f697ec0bad34",
                            Surname = "Hansen",
                            TwoFactorEnabled = false,
                            UserName = "customerlogon",
                            UserType = 1
                        },
                        new
                        {
                            Id = "52fac4db-3d93-46bc-81ef-f33aed467669",
                            AccessFailedCount = 0,
                            Address = "3 Bond End, Monks Kirby, Rugby, UK",
                            ConcurrencyStamp = "aca93244-a896-4dba-b98b-a3ed0fe9a40a",
                            Email = "petelampy@gmail.com",
                            EmailConfirmed = true,
                            Forename = "Amos",
                            HouseNumber = 3,
                            LockoutEnabled = false,
                            NormalizedEmail = "PETELAMPY@GMAIL.COM",
                            NormalizedUserName = "CUSTOMERLOGON2",
                            PasswordHash = "AQAAAAIAAYagAAAAEFBO3OjDAGk0SRerZZU6d2F0SDH/MaFTXhYG51U35lZloko73FzhWxmvYAucigLsBA==",
                            PhoneNumberConfirmed = false,
                            PostCode = "CV23 0RD",
                            SecurityStamp = "ae2960ac-d6e4-4f20-a436-0132d733b06a",
                            Surname = "Burton",
                            TwoFactorEnabled = false,
                            UserName = "customerlogon2",
                            UserType = 1
                        },
                        new
                        {
                            Id = "16776aef-a5ff-424d-be7e-ea3fd591ce90",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b0778bac-54bc-4acf-8a8d-bbda4f030269",
                            Email = "petelampy@gmail.com",
                            EmailConfirmed = true,
                            Forename = "Din",
                            LockoutEnabled = false,
                            NormalizedEmail = "PETELAMPY@GMAIL.COM",
                            NormalizedUserName = "DRIVERLOGON",
                            PasswordHash = "AQAAAAIAAYagAAAAEM2URZ1uWsnzu7wEbH2T3lhaO3Eb8oIoDyO1viPwJ4sumuZz5M5SDiWMKvZ5HFVsdA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "23ba4aea-287b-412a-8b0b-283d4faf994f",
                            Surname = "Djarin",
                            TwoFactorEnabled = false,
                            UserName = "driverlogon",
                            UserType = 2
                        },
                        new
                        {
                            Id = "ca6f5584-527f-4820-802f-bd329352c3e5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5fe5a4cf-421c-4684-b7c6-ddeaae02dcea",
                            Email = "petelampy@gmail.com",
                            EmailConfirmed = true,
                            Forename = "William",
                            LockoutEnabled = false,
                            NormalizedEmail = "PETELAMPY@GMAIL.COM",
                            NormalizedUserName = "EMPLOYEELOGON",
                            PasswordHash = "AQAAAAIAAYagAAAAEDpaYaSuIjf2PP+zu5lAArK2jvRINyx3V/5sVst4C+ziInM4FrTE4fPA/ovMNlBJCA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b2bc1712-c6f0-4729-8165-4e38bf51b294",
                            Surname = "Riker",
                            TwoFactorEnabled = false,
                            UserName = "employeelogon",
                            UserType = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DeliverySoftware.Business.Users.DeliveryUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DeliverySoftware.Business.Users.DeliveryUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliverySoftware.Business.Users.DeliveryUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DeliverySoftware.Business.Users.DeliveryUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
